// <auto-generated />
using System;
using BloodOnTheWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BloodOnTheWeb.Migrations
{
    [DbContext(typeof(SessionContext))]
    [Migration("20200513074858_Seats to Session")]
    partial class SeatstoSession
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BloodOnTheWeb.Models.Player", b =>
                {
                    b.Property<Guid>("PlayerID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PlayerSeat");

                    b.Property<string>("SessionId");

                    b.HasKey("PlayerID");

                    b.HasIndex("SessionId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("BloodOnTheWeb.Models.Session", b =>
                {
                    b.Property<string>("SessionId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("LastUsed");

                    b.Property<int>("Seats");

                    b.HasKey("SessionId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("BloodOnTheWeb.Models.Player", b =>
                {
                    b.HasOne("BloodOnTheWeb.Models.Session", "Session")
                        .WithMany("Players")
                        .HasForeignKey("SessionId");
                });
#pragma warning restore 612, 618
        }
    }
}
